FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker.io docker-compose

# docker group 추가 및 jenkins 유저를 추가
RUN groupadd -F docker && usermod -aG docker jenkins

# 퍼미션 문제 방지
RUN [ -S /var/run/docker.sock ] && chown root:docker /var/run/docker.sock || true

USER jenkins