services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./downloads:/downloads  
    restart: unless-stopped


  playwright-crawler:
      build:
        context: .
      container_name: playwright-crawler
      volumes:
        - ./downloads:/app/downloads
        - ./cmd/start_playwright.sh:/app/start_playwright.sh  
      working_dir: /app
      network_mode: host
      entrypoint: /bin/sh
      command: []
        # - -c
        # - |
        #   chmod +x /app/start_playwright.sh
        #   /app/start_playwright.sh

  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "--socks5-hostname", "127.0.0.1:9050", "-s", "https://check.torproject.org/"]
      interval: 20s
      timeout: 10s
      retries: 5

  curl-crawler:
    image: python:3.11-alpine
    container_name: curl-crawler
    depends_on:
      torproxy:
        condition: service_healthy
    volumes:
      - ./downloads:/app/downloads
      - ./cmd/start_curl.sh:/app/start_curl.sh   
      - ./crawl_with_curl.py:/app/crawl_with_curl.py
    working_dir: /app
    network_mode: host
    entrypoint: /bin/sh
    command:
      - -c
      - |
        apk add --no-cache curl
        pip install pysocks requests       
        chmod +x /app/start_curl.sh
        /app/start_curl.sh
