services:
  playwright-crawler:
    build:
      context: ./playwright-crawler
      dockerfile: Dockerfile.playwright
    container_name: playwright-crawler
    volumes:
      - ./downloads:/app/downloads
    working_dir: /app
    network_mode: host
    command: ["node", "crawl_ransomewatch.js"]
    restart: unless-stopped

  node-crawler:
    build:
      context: ./node-crawler
      dockerfile: Dockerfile.node  
    container_name: node-crawler
    volumes:
      - ./downloads:/app/downloads
    working_dir: /app
    network_mode: host
    command: ["node", "crawl_bleeping_computer.js"]
    restart: unless-stopped

  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "--socks5-hostname", "127.0.0.1:9050", "-s", "https://check.torproject.org/"]
      interval: 20s
      timeout: 10s
      retries: 5

  curl-crawler:
    image: python:3.11-alpine
    container_name: curl-crawler
    depends_on:
      torproxy:
        condition: service_healthy
    volumes:
      - ./downloads:/app/downloads
      - ./scripts/start_curl.sh:/app/start_curl.sh   
      - ./crawl_with_curl.py:/app/crawl_with_curl.py
    working_dir: /app
    network_mode: host
    entrypoint: /bin/sh
    command:
      - -c
      - |
        apk add --no-cache curl
        pip install pysocks requests       
        chmod +x /app/start_curl.sh
        /app/start_curl.sh
