pipeline {
    agent any
    stages {
        stage('Build playwright-crawler') {
            steps {
                echo '📦 playwright-crawler 빌드 중...'
                sh 'docker build -t playwright-crawler -f Dockerfile.playwright .'
            }
        }

        stage('Run Playwright Crawlers') {
            steps {
                echo '🚀 크롤러 실행'
                sh 'docker run --rm -v "$PWD/downloads:/app/downloads" playwright-crawler sh -c "chmod +x /app/start_playwright.sh && /app/start_playwright.sh gbhackers"'
            }
        }
    }
}
