FROM mcr.microsoft.com/playwright:v1.51.1-jammy

WORKDIR /app

RUN npm init -y
RUN npm install playwright@1.51.1
RUN npm install axios
RUN npm install socks-proxy-agent

COPY . .

CMD ["bash", "-c", "node crawl_ransomewatch.js && sleep infinity"]